[www]
user = www-data
group = www-data

; Escuta em todas as interfaces para permitir conexão do nginx em outro container
listen = 0.0.0.0:9000

listen.owner = www-data
listen.group = www-data
listen.mode = 0660

pm = dynamic
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 35
pm.max_requests = 500

; Permite que o nginx repasse variáveis de ambiente ao PHP-FPM
clear_env = no
